<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OsuTweaks</AssemblyName>
    <PackageId>osu-tweaks</PackageId>
    <Title>osu!tweaks</Title>
    <Description>Коллекция полезных твиков и улучшений интерфейса для osu!cc.</Description>
    <Version>1.1.1</Version>
    <Priority>50</Priority>
    <IconGlyph>SlidersH</IconGlyph>
    <IsPlugin>true</IsPlugin>
    <RepositoryUrl>https://github.com/Meyblow/osu-tweaks</RepositoryUrl>
    <PackageTags>menu;song-select;settings;tools;ui;gameplay</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Author Include="Meyblow" OsuProfileId="39791134" />
  </ItemGroup>

  <ItemGroup>
    <PluginDocument Include="README.md" Title="README" IconGlyph="Book" />
    <PluginDocument Include="CHANGELOG.md" Title="Changelog" IconGlyph="History" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="osucc.Api" Version="2.2.0" />
    <PackageReference Include="osucc.Build" Version="2.2.0" PrivateAssets="all" />
    <PackageReference Include="ppy.osu.Game" Version="2026.702.1" />
  </ItemGroup>

</Project>
